"""Stage-5.sim task: the plan-model search narrative for a position.

The response is the token-mode flatten of the alpha-beta tree the plan model's
candidates span (datagen.sim.search + datagen.sim.flatten): plans at every
node, verdict leaves, forced key variations, solid conclusions, supersession
events — all in the stage POV-token vocabulary, anchored at the root mover.

Generation needs the two stage-5 models on a GPU with the batched sampler, so
this task is NOT computed inside build_qa_dataset: run the sharded GPU array
(datagen.sim.parallelize run / scripts/datagen/datagen_stage5sim.sbatch) and
pack the shard jsonls with `python -m datagen.sim.parallelize pack` (or
build_qa_dataset --stage5sim-pack). The module exists so configs can name the
task and the packed arrows carry its NAME/PROMPT.
"""

NAME = "sim_rationale"
MAX_UNIQUE_QUERIES = 1
PARALLEL_ANALYZE = True
PROMPT = "Analyze the position carefully and find the best move for player."


def analyze(triples):
    raise NotImplementedError(
        "sim_rationale is generated by the sharded GPU runner "
        "(datagen.sim.parallelize run) and packed with "
        "`python -m datagen.sim.parallelize pack`; it cannot be computed "
        "inside build_qa_dataset.")
