"""Per-module natural statistics for continuous atomic factors.

Auto-generated by build_factor_stats.py over 934458 positions
(65542 in-check skipped) from data/lichess/forward/train-*.jsonl.
Datapoints are own-side module values (both sides pooled), firing-only.
(mu, sigma) given separately for raw mg and eg; not interpolated.
"""

CONTINUOUS_STATS = {
    'bishop pawns': {'n': 1517222, 'mg': (-37.57, 24.16), 'eg': (-87.66, 56.38)},
    'connected': {'n': 1784911, 'mg': (109.64, 42.15), 'eg': (-0.74, 19.79)},
    'flank attacks': {'n': 1856082, 'mg': (-66.96, 27.52), 'eg': (0.0, 0.0)},
    'hanging': {'n': 446222, 'mg': (79.39, 27.57), 'eg': (41.42, 14.38)},
    'king danger': {'n': 746022, 'mg': (-211.95, 409.06), 'eg': (-44.22, 37.44)},
    'king protector': {'n': 1696135, 'mg': (-52.34, 23.12), 'eg': (-59.82, 26.42)},
    'knight on queen': {'n': 160115, 'mg': (20.6, 7.76), 'eg': (15.45, 5.82)},
    'material': {'n': 1868916, 'mg': (7297.77, 2456.87), 'eg': (8061.15, 2701.25)},
    'mobility': {'n': 1832670, 'mg': (66.88, 69.21), 'eg': (191.04, 130.38)},
    'passed': {'n': 304572, 'mg': (78.42, 148.13), 'eg': (105.72, 173.57)},
    'pawn push threat': {'n': 464313, 'mg': (54.22, 17.13), 'eg': (44.05, 13.92)},
    'restricted': {'n': 1836728, 'mg': (45.28, 23.76), 'eg': (45.28, 23.76)},
    'safe pawn threat': {'n': 95051, 'mg': (177.9, 29.03), 'eg': (96.66, 15.77)},
    'shelter/storm': {'n': 1868916, 'mg': (101.31, 90.05), 'eg': (-13.47, 9.16)},
    'slider on queen': {'n': 223054, 'mg': (72.7, 34.78), 'eg': (22.18, 10.61)},
    'space': {'n': 1196095, 'mg': (106.35, 31.06), 'eg': (0.0, 0.0)},
    'threat by minor': {'n': 748358, 'mg': (43.1, 41.56), 'eg': (58.22, 44.56)},
    'threat by rook': {'n': 250028, 'mg': (13.44, 17.81), 'eg': (54.63, 20.65)},
}
